"""empty message

Revision ID: 03973730ff73
Revises: 7bfac9bb5e73
Create Date: 2020-05-12 14:44:50.576458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03973730ff73'
down_revision = '7bfac9bb5e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'cuisine_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('cuisine_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'rating', 'cuisine', ['cuisine_id'], ['id'])
    # ### end Alembic commands ###
