"""empty message

Revision ID: 2d86810e63ae
Revises: 03973730ff73
Create Date: 2020-05-12 14:46:27.957733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d86810e63ae'
down_revision = '03973730ff73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rating_date_posted', table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rest_id', sa.INTEGER(), nullable=True),
    sa.Column('cuisine_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.ForeignKeyConstraint(['rest_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rating_date_posted', 'rating', ['date_posted'], unique=False)
    # ### end Alembic commands ###
