"""empty message

Revision ID: 6ebb1152fe88
Revises: 6238156a118a
Create Date: 2020-05-12 15:30:42.503118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebb1152fe88'
down_revision = '6238156a118a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_restaurant_name', table_name='restaurant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_restaurant_name', 'restaurant', ['name'], unique=1)
    # ### end Alembic commands ###
