"""empty message

Revision ID: 7bfac9bb5e73
Revises: 7fc93045acde
Create Date: 2020-05-12 14:23:16.742030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfac9bb5e73'
down_revision = '7fc93045acde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('has__cuisine')
    op.drop_table('has__rating')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'cuisine_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('cuisine_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'rating', 'cuisine', ['cuisine_id'], ['id'])
    op.create_table('has__rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rest_id', sa.INTEGER(), nullable=True),
    sa.Column('cuisine_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('rating_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.ForeignKeyConstraint(['rest_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('has__cuisine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rest_id', sa.INTEGER(), nullable=True),
    sa.Column('cuisine_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.ForeignKeyConstraint(['rest_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
