"""empty message

Revision ID: f60ca8ea298a
Revises: 82f531dbe1ee
Create Date: 2020-05-12 15:28:40.760548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60ca8ea298a'
down_revision = '82f531dbe1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('cuisine', sa.String(), nullable=True))
    op.drop_column('restaurant', 'cusine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('cusine', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurant', 'cuisine')
    # ### end Alembic commands ###
